# Generated by Django 3.2.25 on 2024-10-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_pdffile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdffile',
            options={'ordering': ['-upload_date']},
        ),
        migrations.AddField(
            model_name='pdffile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
