# Generated by Django 3.2.25 on 2025-02-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_alter_message_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdffile',
            name='year_published',
            field=models.DateField(),
        ),
    ]
