# Generated by Django 3.2.25 on 2025-02-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0008_alter_pdffile_year_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdffile',
            name='year_published',
            field=models.IntegerField(),
        ),
    ]
