# Generated by Django 3.2.25 on 2025-02-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0009_alter_pdffile_year_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='day_published',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='pdffile',
            name='month_published',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
